name: expense_manager
description: A personal finance manager built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Architecture & State Management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Network
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true